version: '3'
services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-api
    depends_on:
      - redis
      - worker
  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/flask-api
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
  redis:
    image: redis
    ports:
      - "6379:6379"