version: '3'
services:
  ui:
    build: ./ui
    stdin_open: true
    tty: true
    depends_on:
      - web
    ports:
      - '3000:3000'
    volumes:
      # - ftp-data:/usr/src/node-app/ftp-dir
      - ./ui/src:/usr/src/node-app/src
    container_name: ui-dev
    # command: npm run serve
    command: npm run dev
  web:
    build: ./api
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./api:/flask-api
      - ./api/musicFiles/:/musicFiles
    depends_on:
      - redis
      - worker
  worker:
    build: ./api
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./api:/flask-api
      - ./api/musicFiles/:/musicFiles
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  musicFiles: